#!/usr/bin/env python3

from optparse import OptionParser


if __name__ == "__main__":
    usage = "usage: %prog [options]"
    parser = OptionParser(usage=usage)
    parser.add_option("--url", dest="url", help="URL to create a site for.")

    options, args = parser.parse_args()

    if not (options.url):
        parser.error("You must provide a URL to create a site for")

